### ISSUE TITLE
LOINC 1742-6 Alanine aminoransferase in serum or blood

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#101]
The L value was mapped to HP:0031965 Elevated serum alanine aminitransferase. I Believe it is a mistake and have removed it. @LCCarmody

**Comment by callahantiff** [comment]
@nicolevasilevsky had verified this annotation in my spreadsheet and said it was correct for a low lab result if it was negated. That's how I have it listed. Is that now not correct?

**Comment by nicolevasilevsky** [comment]
@kingmanzhang what should we do in these cases? Should we leave the low value blank?

**Comment by kingmanzhang** [comment]
Sorry it must be my software bug that overwrites your negation. I think we should leave the low value blank if we think low value is normal. (Also because of my software bug, we have to leave it blank now. --will fix later). I will talk to Peter about this.

**Comment by callahantiff** [comment]
Ok, sounds good!

**Comment by kingmanzhang** [comment]
done
