### ISSUE TITLE
LOINC 8453-3, 8454-1, 8455-8 blood pressure

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#102]
The L and H mappings seem flipped. I have switched them back. @callahantiff

**Comment by callahantiff** [comment]
Weird! Something must have transferred over incorrectly because they are OK in my original copy. Sorry about that and thanks for adjusting!

**Comment by kingmanzhang** [comment]
done
