### ISSUE TITLE
review LOINC 3040-3 Lipase(Enzymatic activity/volume)

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#103]
@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
this looks good to me

**Comment by pnrobinson** [comment]
I think the problem is that there are multiple lipases, and I am not sure which this is. Could this be a legacy test that is not used much anymore or do people still test for generic lipase activity?

**Comment by nicolevasilevsky** [comment]
according to these articles, it seems like generic lipase activity tests are still done:
https://www.healthline.com/health/lipase-test
https://www.ncbi.nlm.nih.gov/pubmed/27015625

**Comment by pnrobinson** [comment]
live&learn :=0

**Comment by pnrobinson** [comment]
added annotation
