### ISSUE TITLE
LOINC 15152-2 is Qn

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#105]
It is a quantitative test and should not be mapped to positive, negative codes.

**Comment by kingmanzhang** [comment]
@callahantiff

**Comment by callahantiff** [comment]
Yes, totally right! Sorry for not including those. I have a question on the annotation, but am meeting with Nicole tomorrow to clarify them. I can post here after the meeting.

**Comment by callahantiff** [comment]
Looks like the following annotations should be made:
  - **Normal:** NOT(HP:0002908)
  - **Low:** None
  - **High:** HP:0002908

Low levels of this lab do not seem to be problematic. An annotation to the high result should already exist (made on 2018-05-08T08:42:38).

**Comment by pnrobinson** [comment]
The fix seems to have been already implemented, thanks
