### ISSUE TITLE
LOINC 3034-6: Transferrin [Mass/volume] in Serum or Plasma (update annotation)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#107]
With the new terms added for transferrin (see [issue # 4139](https://github.com/obophenotype/human-phenotype-ontology/issues/4139)), we will want to update the following annotations:
  - **Normal:** NOT(HP:0011031) -->  NOT(HP:0032385)
  - **Low:** HP:0011031 -->  HP:0032387
  - **High:** HP:0011031 -->  HP:0032386

**Comment by kingmanzhang** [comment]
done
