### ISSUE TITLE
LOINC 2397-8  Glycoproteins [Presence] in Urine

### ISSUE THREAD

**Issue by jpgourdine** [TheJacksonLaboratory/loinc2hpoAnnotation#121]
@pnrobinson @nicolevasilevsky Should we create a child term for presence of glycoproteins in urine (parent term Proteinuria, HP:0000093) or just match it with Proteinuria (HP:0000093)?

Contrary to glycopeptides,  aminoglycans and free glycans, I have not found significant lab test on presence of glycoproteins in the urine (there are present in the urine in the controls, specific ones might be indicative of certain diseases see [PMID: 21459797](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3096687/))

**Comment by pnrobinson** [comment]
I found this
Increased urinary orosomucoid HP:0032377 (synonym   Increased urinary alpha-1-acid glycoprotein)

40600-9 Alpha-1-acid glycoprotein [Presence] in Urine by Immunoelectrophoresis

Adding this annotation.
