### ISSUE TITLE
robot and dosdp-tools

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#122]
Amy reported that they are now required for building hp.obo. To test this and revise documentation.

**Comment by pnrobinson** [comment]
They are only necessary if we want to create an hp.obo between builds. It is better, now that we have lots of annotations, just to take the main hp.obo file and to not use the hp-edit.owl file at all.

**Comment by kingmanzhang** [comment]
We are only doing this for our biocurators. They will still need to build hp.obo between builds if they want to annotate with newly created terms.

**Comment by kingmanzhang** [comment]
done
