### ISSUE TITLE
A code

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#134]
We have some annotations like this:
```
4542-7	Qn	FHIR	L	HP:0020181	false	2020-06-07T21:50:31	JAX:azhang	NA	NA	0.1	true	NA
4542-7	Qn	FHIR	N	HP:0020179	true	2020-06-07T21:50:31	JAX:azhang	NA	NA	0.1	true	NA
4542-7	Qn	FHIR	H	HP:0020180	false	2020-06-07T21:50:31	JAX:azhang	NA	NA	0.1	true	NA
4542-7	Qn	FHIR	A	HP:0020179	false	2020-06-07T21:50:31	JAX:azhang	NA	NA	0.1	true	NA
```
but also a few like this
```
2823-3	Qn	FHIR	N	HP:0011042	true	2018-03-20T15:34:05	JGM:Aaron	NA	NA	0.1	true	NA
2823-3	Qn	FHIR	H	HP:0002153	false	2018-03-20T15:34:05	JGM:Aaron	NA	NA	0.1	true	NA
2823-3	Qn	FHIR	L	HP:0002900	false	2018-03-20T15:34:05	JGM:Aaron	NA	NA	0.1	true	NA
```
I think we can drop the annotations with the 'A" code because we can infer them from the 'N' code. Also, there is no need to has the isNegated column because the 'N' code is always negated and none of the other codes are negated.

**Comment by kingmanzhang** [comment]
The initial thinking was "A" might be annotated differently than pure negation of "N". But in later annotation it did not happen. So in this sense, "A" can be removed. 

(A slight downside is in the use of the file. "A" would probably appear in transformed lab results. We will let a user know that they need to figure out the annotations from "N" to "A" for themselves.)

**Comment by pnrobinson** [comment]
Well, I guess one of the most important rules in software development is to not duplicate things. Having N and A annotations that mean almost the same things would be a source of confusion for users of the file or of the library. I think we also need to imrove the documentation to cover this though

**Comment by kingmanzhang** [comment]
Agreed

**Comment by pnrobinson** [comment]
implemented.
