### ISSUE TITLE
Narrative annotations

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#140]
We have the following annotations
```
19263-3	Nar	N	HP:0031840	.	HPO:nvasilevsky[2018-12-18]	.
19263-3	Nar	POS	HP:0500112	.	HPO:nvasilevsky[2018-12-18]	.
19263-3	Nar	H	HP:0500112	.	HPO:nvasilevsky[2018-12-18]	.
19263-3	Nar	NEG	HP:0031840	.	HPO:nvasilevsky[2018-12-18]	.
```
but I do not think we are able to handle narrative annotations with this kind of outcome code. @callahantiff @kingmanzhang @nicolevasilevsky @iimpulse
I would suggest removing this because we cannot decode it without knowing what do do with narrative outcomes.

Nicole, do you remember the use case?

**Comment by pnrobinson** [comment]
Here is a full list of NAR annotations that I am skipping for now. We can re annotate them if desired.

Skipping annotation because scale==Unknown
35094-2 (Unknown/N): HP:0030972 ; JGM:azhang[2018-06-19T17:27:29]
Skipping annotation because scale==Unknown
35094-2 (Unknown/POS): HP:0000822 ; JGM:azhang[2018-06-19T17:27:29]
Skipping annotation because scale==Unknown
35094-2 (Unknown/H): HP:0000822 ; JGM:azhang[2018-06-19T17:27:29]
Skipping annotation because scale==Unknown
35094-2 (Unknown/NEG): HP:0030972 ; JGM:azhang[2018-06-19T17:27:29]
Skipping annotation because scale==Unknown
35094-2 (Unknown/L): HP:0002615 ; JGM:azhang[2018-06-19T17:27:29]
Skipping annotation because scale==Unknown
53745-6 (Unknown/N): HP:0031840 ; HPO:nvasilevsky[2018-12-18T15:20:29]
Skipping annotation because scale==Unknown
53745-6 (Unknown/POS): HP:0500111 ; HPO:nvasilevsky[2018-12-18T15:20:29]
Skipping annotation because scale==Unknown
53745-6 (Unknown/H): HP:0500111 ; HPO:nvasilevsky[2018-12-18T15:20:29]
Skipping annotation because scale==Unknown
53745-6 (Unknown/NEG): HP:0031840 ; HPO:nvasilevsky[2018-12-18T15:20:29]
Skipping annotation because scale==Nar
19263-3 (Nar/N): HP:0031840 ; HPO:nvasilevsky[2018-12-18T15:25:12]
Skipping annotation because scale==Nar
19263-3 (Nar/POS): HP:0500112 ; HPO:nvasilevsky[2018-12-18T15:25:12]
Skipping annotation because scale==Nar
19263-3 (Nar/H): HP:0500112 ; HPO:nvasilevsky[2018-12-18T15:25:12]
Skipping annotation because scale==Nar
19263-3 (Nar/NEG): HP:0031840 ; HPO:nvasilevsky[2018-12-18T15:25:12]

**Comment by nicolevasilevsky** [comment]
@pnrobinson No, I don't remember the exact use case. I have no issues with removing these.

**Comment by pnrobinson** [comment]
OK, let's remove them for now, it is not worth adding the logic for these annotations unless we had a ton of them
