### ISSUE TITLE
group annotations together

### ISSUE THREAD

**Issue by nicolevasilevsky** [TheJacksonLaboratory/loinc2hpoAnnotation#15]
@kingmanzhang would it be possible to create a functionality where you could annotate multiple LOINC codes at once? For example, there are a bunch of glucose measurements in urine (or blood) at various time points. I pasted a screenshot below. It would be nice if we could annotate these in bulk, rather than one at a time.

![image](https://user-images.githubusercontent.com/6722114/40031152-4c0a77ac-57bc-11e8-87b2-429e97c851e3.png)

**Comment by kingmanzhang** [comment]
Technically that's easy to implement. I will code it up today and let you try out.

**Comment by nicolevasilevsky** [comment]
Cool, thanks!

**Comment by nicolevasilevsky** [comment]
No worries, no rush!

**Comment by kingmanzhang** [comment]
addressed
