### ISSUE TITLE
question about increased/decreased/abnormal fields

### ISSUE THREAD

**Issue by nicolevasilevsky** [TheJacksonLaboratory/loinc2hpoAnnotation#21]
I don't understand why sometimes you see an abnormal field and increased and decreased fields for LOINC annotations, and something there is just abnormal and increased only?

**Comment by pnrobinson** [comment]
If something is normally not present at all then it cannot be abnormally reduced!

**Comment by nicolevasilevsky** [comment]
So, for the codes with Glucose‐6‐phosphate dehydrogenase, many of the codes only gave me a abnormal or high value field. 

I'm did some more research about lab tests for Glucose‐6‐phosphate dehydrogenase, and it seems that sometimes the enzyme is decreased (like in anemia, it is decreased in red blood cells) and sometimes it is increased (like in adipose cells in obese patients, or in [tumor cells in a cervical cancer](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4935254/)).

I have two questions:
1. I had added abnormal/increased/decreased Glucose‐6‐phosphate dehydrogenase levels in [location] for all the various locations where they were measuring G6PD in the LOINC codes. But I should review those and make sure all those terms are actually needed, yes? (I started going through those already and adding references, were applicable.)
2. There should be some adjustments to the LOINC2HPO app, so they low value field is available for the G6DP measurements, yes? @kingmanzhang

**Comment by nicolevasilevsky** [comment]
According to this [paper](https://iubmb.onlinelibrary.wiley.com/doi/full/10.1002/iub.137), in table 1, there is sometimes increased activity of G6DP (but they don't say where it is measured). So maybe it is okay to keep the increased level terms?

Looks like the LOINC codes also detect the presence and activity. So we need abnormal activity terms too (increased and decreased)?

**Comment by kingmanzhang** [comment]
I am not sure I understand everything you said. When did you not see low value field for G6DP? I turned off low value field if the LOINC code has "presence/absence" outcome (LOINC name has "Presence" in square bracket). In this case, the outcome can only be positive/present, or negative/absent.

**Comment by kingmanzhang** [comment]
I am closing it for now.
