### ISSUE TITLE
Ammonia terms == do not map

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#31]
https://github.com/obophenotype/human-phenotype-ontology/issues/3616

**Comment by nicolevasilevsky** [comment]
I annotated some of the ammonia terms as 'unableto_annotate'.

I have questions about a few of them:
1. Latex glove extract ammoniated IgE Ab RAST class [Presence] in Serum (or blood) -> _should this be unable to annotate?_ 
  a. There is also Latex glove extract ammoniated IgE Ab [Units/volume] in Serum
2. Ammonia nitrogen [Mass/time] in 24 hour urine -> _should I make a NTR?_
3. Carbamoyl phosphate synthetase (ammonia) [Enzymatic activity/mass] in Tissue -> _should I make a NTR?_
4. Histidine ammonia lyase [Enzymatic activity/volume] in Serum -> _should I make a NTR?_
5. Ammonia/Creatinine [Molar ratio] in 24 hour Urine -> _should I make a NTR?_

**Comment by pnrobinson** [comment]
Closing this, see comments in https://github.com/obophenotype/human-phenotype-ontology/issues/3616
