### ISSUE TITLE
New feature request - bulk annotate 'unspecified' terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [TheJacksonLaboratory/loinc2hpoAnnotation#32]
See https://github.com/obophenotype/human-phenotype-ontology/issues/3588#issuecomment-403252288

@kingmanzhang would there be a way to bulk annotate terms that have unspecified specimens, as unableto_annotate? There are lots of these and annotating them one by one will take a while!

**Comment by kingmanzhang** [comment]
addressed.

**Comment by callahantiff** [comment]
@pnrobinson following up on our conversation today, I investigated a sample of these types of LOINC codes in our database and found that their frequency of use in practice ranged widely (see below):  
  - LOINC 20599-7   (n=9024)
  - LOINC 20593-0 (n=6028)
  - LOINC 20592-2 (n=5869)
  - LOINC 35663-4 (n=5400)
  - LOINC 22743-9 (n=4924)
  - LOINC 47797-6 (n=4893)
  - LOINC 47725-7 (n=4818)
  - LOINC 21166-4 (n=1533)
  - LOINC 22733-0 (n=17)
  - LOINC 56472-4 (n=10)
  - LOINC 25836-8 (n=5)
  - LOINC 20608-6 (n=2)
  - LOINC 35675-8 (n=2)
  - LOINC 20595-5 (n=1)
