### ISSUE TITLE
clusters of LOINC tests

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#33]
Many LOINC tests are about the same medical problem. If we each focus on a couple and read relevant literature thoroughly, we will be able to annotate more efficiently. I suggest each (or two) of us pick a couple topics and address all related LOINC tests (using "search" to get all related LOINC tests).

- [ ] transferrin/ion: iron,iron binding capacity, transferrin free, transferrin capacity, transferrin saturation (search with "iron" or "transferrin" to get all LOINC tests to annotate) ...
- [x] blood cells in urine: leukocytes in urine, erythrocyte in urine, basophil in urine ...
- [x] immune cell types in blood: search with "CD cell"
- [ ] coagulation assays: PT, PTT, INR, various factors ...
- [x] blood acidity: lactate, base, bicarbonate, pH, etc.
- [x] Endocrine gland hormones: T3, T4, cortisol, testosterone, prolactin, insulin/proinsulin/C peptide
- [x] urinalysis of compounds: bilirubin (all forms) in urine

to continue...

**Comment by jpgourdine** [comment]
@kingmanzhang sound good, I will go for the metabolomics related terms (urinalysis and blood acidity)

**Comment by kingmanzhang** [comment]
I studied endocrine peptide secretion before so I will take care of this.

**Comment by nicolevasilevsky** [comment]
I'll take blood cells in urine and immune cell types in blood

**Comment by nicolevasilevsky** [comment]
for the CD terms, see related ticket: https://github.com/obophenotype/human-phenotype-ontology/issues/4014

**Comment by pnrobinson** [comment]
I am going to close this since we are just about to start a new wave of annotations and we will see any common annotations that are missing
