### ISSUE TITLE
viral infection

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#35]
There are many tests on viral antigen or presence of anti-viral antibodies. Do we want to create term for each? We could map all such tests to Severe viral infection for now and create HPO terms in future. 
e.g.
HSV IgM Ab in serum
HBV core Ag
HBV surface Ag
HSV 1 Ag
...

**Comment by pnrobinson** [comment]
IgM often follows an acute infection but the other antibody types persist after infection. This will require a case by case analysis, I will close this now but we do need a better way of dealing with all of the antibodies -- this is what the supplemental ontology term could be
