### ISSUE TITLE
Sputum eosinophilia

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#39]
see if there is a LOINC code for this.
https://github.com/obophenotype/human-phenotype-ontology/issues/4008

**Comment by nicolevasilevsky** [comment]
there is:

- Loinc: 10327-5 [Eosinophils/100 leukocytes in Sputum by Manual count] 
- Loinc: 29993-3 [Eosinophils [Presence] in Sputum by Wright stain] 
- Loinc: 30381-8 [Eosinophils/100 leukocytes in Sputum]

**Comment by kingmanzhang** [comment]
done
