### ISSUE TITLE
CBC HPO Terms added for LOINC

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#42]
@kingmanzhang  -- I think we now have all terms needed for the CBC

https://github.com/obophenotype/human-phenotype-ontology/issues/3863

https://github.com/obophenotype/human-phenotype-ontology/issues/3510

https://github.com/obophenotype/human-phenotype-ontology/issues/3490

**Comment by kingmanzhang** [comment]
resolved
