### ISSUE TITLE
International Normalized Ratio (INR) in platelet poor plasma by coagulation assay (LOINC: 6301-6)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#50]
This LOINC code is currently annotated to HP:0003540 (impaired platelet aggregation). This HPO concept is defined as "An impairment in the rate and degree to which platelets aggregate after the addition of an agonist that stimulates platelet clumping. Platelet aggregation is measured using aggregometer to measure the optical density of platelet-rich plasma, whereby platelet aggregation causes the plasma to become more transparent." 

If the LOINC term is defined as a test in "platelet poor plasma", but the HPO term is referencing "platelet-rich plasma", perhaps this is an incorrect annotation?

**Comment by kingmanzhang** [comment]
revised according to https://github.com/obophenotype/human-phenotype-ontology/issues/3511

**Comment by kingmanzhang** [comment]
done
