### ISSUE TITLE
Tomato IgE Ab [Units/volume] in Serum (6266-1)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#51]
This LOINC code has been annotated to HP:0410238 (Increased anti-plant product IgE antibody level).  This concept is defined as "Increased level of IgE antibody against antigens from plants and products derived from plants, such as wood or pollen."

Should it instead be annotated to HP:0410228 (Increased anti-plant based food allergen IgE antibody level)?

**Comment by kingmanzhang** [comment]
I saw it corrected now.
