### ISSUE TITLE
American house dust mite IgE Ab [Units/volume] in Serum (6095-4)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#52]
This LOINC term is annotated to HP:0410248 (Increased anti-house dust IgE antibody level). 

Would it be more correct to annotate this LOINC term to HP:0410223 (Increased anti-dust mite IgE antibody level) instead?

**Comment by kingmanzhang** [comment]
@nicolevasilevsky @pnrobinson Maybe change the label of HP:0410248  to *Increased anti-house dust mite IgE antibody level*?

**Comment by nicolevasilevsky** [comment]
I updated the label to 'Increased anti-house dust mite IgE antibody level', and made 'Increased anti-dust mite IgE antibody level' a synonym.
