### ISSUE TITLE
Erythrocyte distribution width [Ratio] by Automated count (788-0)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#53]
LOINC term is annotated to HP:0031965 (Increased RBC distribution width). There is no term for decreased RBC distribution width in the HPO. Can this be annotated to the nearest ancestor concept HP:0001877 (Abnormal erythrocyte morphology)?

**Comment by callahantiff** [comment]
That's a good question. I found this [post](https://www.researchgate.net/post/What_is_the_significance_of_low_RDW_RBC_Distribution_Width_particularly_in_the_presence_of_normal_blood_profiles) from ResearchGate to be helpful. One particular post states, "A low RDW (below 10.2%) means that the red blood cells vary very little in size. One reason for a low RDW level is macrocytic anemia. Another cause of a low RDW level is microcytic anemia. In these two disorders the red blood cells do not vary much in size because they are either all small or all large. This is what causes the RDW level to be low". What I mainly take from this post is that a measure of low RBC width can be useful when combined with other measures to make a diagnosis (in this case for a type of anemia). I was trying to find a way to represent it for that reason.

The main thing I wanted to note with this issue is that in the LOINC2HPO annotations, this LOINC test, for a low result, is currently annotated to HP:0031965, which is the concept for increased RBC distribution.

Sorry if I added confusion by also suggesting a separate annotation that could be used.

**Comment by pnrobinson** [comment]
I will try to run this down. A quick glance shoed the opposite actually,
https://www.ncbi.nlm.nih.gov/pubmed/22187759
https://watermark.silverchair.com/labmed30-0538.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAk0wggJJBgkqhkiG9w0BBwagggI6MIICNgIBADCCAi8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPkSgUYkbpE5X4LIkAgEQgIICAD0lPd6Tpn_t3azTDRYoIoMqEEakcmbNTth6-yBMr48cgFnvTnKSjUbunXPghdekLYpjAnzqAE8LijzB_mbuMIVy5sX10Doi4ddgPBVR8O7hc1fpfVBpDgx8OtcJ4yp_MT6BvGEqEoIJGduxpVOZeoAX-Q7VRAFWMXyIylpfnLDMGmF_hYJm-8iRm7BGqKB75er-6_JL4lqEj1RzQgJuES11Dl4XzUlHzzudKqQSxaFki4pwuhcgTG3VmaMHqwnFeQeVv0IQb6L4cNldclPA9fUqlYxiyKMRWKSBZ1wG6zVwJE56hkvyX3UeMXYJn5n4-17fCEb0_J7sasFBJWfkpGF2yuQopHOGIeRVxv2WU3rD_tFAZ1FJTUkumJWjDsN4uMKiBjbI3pWRqVaSnSDIvAKZ6kvQa93aD1NhbdN0fsNTNaptZ2RU8gtu1hYXwVP3gaZGrdDPx5IR0HaBonoZhZTZwrPUdV6d0qNqMsKUHxELsNNrwiukg177chLM0FL-XdFRPXN8yt4lkHJAw6V-EemM0hJf-NrhVZEKx03lRYmzlX0fgeNdDsoLG-64PPN5a7L7brpKFaRHoc0z9Yo5k8a3sb3VffJ2nxPbDeZquUCAV37QK746O4yUQxRnNo8ALmaKAw2RwmpaU2XN1_OEx4z4VSKe8lz5-y-xfPMIa-9v

**Comment by callahantiff** [comment]
Oh interesting! I will also keep searching and will make a note to ask the clinician-annotators I have been working with.

**Comment by kingmanzhang** [comment]
The L annotation to HP:0031965 is wrong and I have removed it. I am closing this ticket now.
