### ISSUE TITLE
Loinc 32799-9: "Glycosaminoglycans/Creatinine [Mass Ratio] in Urine

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#66]
https://github.com/obophenotype/human-phenotype-ontology/issues/3603

we can add this annotation.
If the result is high -- call the term https://hpo.jax.org/app/browse/term/HP:0003541
if the result is low or normal, call NOT https://hpo.jax.org/app/browse/term/HP:0003541

**Comment by kingmanzhang** [comment]
done
