### ISSUE TITLE
LOINC tests that measure ratios or fractions

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#72]
There are a large number of LOINC tests that measure a ratio (e.g. [LOINC 30065-7](https://r.details.loinc.org/LOINC/30065-7.html?sections=Comprehensive): Cystine/Creatinine [Ratio] in Urine).

@pnrobinson, @nicolevasilevsky mentioned that these types of labs are not currently annotated. Do you anticipate annotating them in the future? Some of these labs are particularly important for diagnosing/confirming/monitoring inborn metabolic disorders, which will be very useful within pediatric populations.

**Comment by pnrobinson** [comment]
SInce the HPO terms are qualitative, can we annotate this simply to Cystinuria? (i.e., both Increased Cystine in Urina and increased ratio?)

**Comment by callahantiff** [comment]
I think that would be totally reasonable for that particular lab.

There are several other ratio tests  (e.g. *Ornithine/Creatinine [Ratio] in Urine, Methionine/Creatinine [Ratio] in Urine*) and ratio mass tests (e.g. *Orotate/Creatinine [Mass Ratio] in Urine, N-octanoylglycine/Creatinine [Mass Ratio] in Urine*) in urine we have results for.

Would we do the same type of thing? If it is easier, I am also happy to submit each test as a separate issue.

**Comment by callahantiff** [comment]
@nicolevasilevsky and I will work on adding new terms for all LOINC codes that measure an amino acid/creatine ratio.

**Comment by kingmanzhang** [comment]
I think this can be closed.
