### ISSUE TITLE
Cerebrospinal fluid amino acid LOINC tests

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#73]
@pnrobinson, many of the cerebrospinal fluid amino acid tests have not yet been annotated to HPO terms. I am hesitant to annotate all of these lab tests as only being an abnormality of the cerebrospinal fluid (HP:0002921) as it would remove important specificity. 

An alternative to creating new HPO terms could be annotating multiple existing HPO terms to a lab test. For example,  [LOINC 22657-1: Alanine [Moles/​volume] in Cerebral spinal fluid](https://r.details.loinc.org/LOINC/22657-1.html?sections=Comprehensive) could be annotated to:   
  - Abnormal circulating alanine concentration (HP:0010916)  
  - Abnormality of the Cerebrospinal Fluid (HP:0002921)  

I'm curious if you would consider this type of an approach acceptable (specifically for these types of labs, but also in general) or if you would prefer that new HPO terms be submitted? 

Adding @nicolevasilevsky to this issue.

**Comment by pnrobinson** [comment]
Hi Tiffany -- "Circulating" means (in this case) in the blood circulation and so this would not work. I am less concerned about making new HPO terms, especially if these tests are being used in practice!

**Comment by callahantiff** [comment]
Yes, sorry that was not the best example. OK, so in this situation, since I am specifically mapping terms from our EHR, I should try suggesting a new term? I just want to make sure I am consistent with your current procedures/philosophy/plan for the HPO.

**Comment by pnrobinson** [comment]
I would suggest let's go through these issues and then find some time to skype? In general the suggestions look great!

**Comment by callahantiff** [comment]
That sounds great. We have some time on your schedule for this exact type of thing (later this month). Looking forward to it!

**Comment by callahantiff** [comment]
Agreed during the meeting to add new HPO terms for all amino acid CSF tests. @nicolevasilevsky and I will work on getting these terms submitted.

**Comment by pnrobinson** [comment]
I do not see any open action item. @callahantiff happy to add more annotations if needed, but we will need to collect the LOINC ids. The new annotation app is ready.

**Comment by callahantiff** [comment]
> I do not see any open action item. @callahantiff happy to add more annotations if needed, but we will need to collect the LOINC ids. The new annotation app is ready.

Sounds great @pnrobinson! I am so pumped about the app! I will download and take a look at it today!
