### ISSUE TITLE
Loinc 30152-3: "Mannose-binding protein [Mass/volume] in Serum"

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#78]
see https://github.com/obophenotype/human-phenotype-ontology/issues/4102

HP_0032306 etc.

**Comment by jpgourdine** [comment]
Hi  Aaron


I am setting up my new computer for LOINC, I got this error

(java.lang.NoClassDefFoundError: javafx/application/Application)

Do you have some free time before between now and 2PM EST?

If not, we can try later tomorrow?

Thanks

**Comment by kingmanzhang** [comment]
done
