### ISSUE TITLE
LOINC 22733-0: Phosphate [Moles/volume] in Unspecified specimen (Remove)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#83]
This lab is a measure of an **Unspecified specimen**, the original annotations for the following results should be removed for reasons described in **issue #32**:  
  - LOINC 22733-0 (Normal) annotated to HP:0100529  
  - LOINC 22733-0 (Low) annotated to HP:0100529

**Comment by kingmanzhang** [comment]
done
