### ISSUE TITLE
LOINC 26466-3: Leukocytes [#/volume] in Body fluid (Remove)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#84]
This lab is a measure of an **Unspecified specimen, body fluid, or substance**, the original annotations for the following results should be removed for reasons described in **issue #32**:  
  - LOINC 26466-3 (Normal) annotated to HP:0011893
  - LOINC 26466-3 (Low) annotated to HP:0001882  
  - LOINC 26466-3 (High) annotated to HP:0001974

**Comment by kingmanzhang** [comment]
done
