### ISSUE TITLE
LOINC 26455-6: Erythrocytes [#/volume] in Body fluid (Remove)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#85]
This lab is a measure of an **Unspecified specimen, body fluid, or substance**, the original annotations for the following results should be removed for reasons described in **issue #32**:  
  - LOINC 26455-6 (Normal) annotated to HP:0020058

**Comment by kingmanzhang** [comment]
done
