### ISSUE TITLE
LOINC 11555-0: Base excess in Blood by calculation (update annotation)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#89]
Per [HPO issue #4021](https://github.com/obophenotype/human-phenotype-ontology/issues/4021) update the annotation for LOINC 11555-0 from NOT(HP:0004360) to NOT(HP:0032281).

**Comment by kingmanzhang** [comment]
done. 
also added H -> HP:0032281
