### ISSUE TITLE
Bacteremia

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#9]
We can add this Loinc annotation, new HPO term:
HP_0031864

**Comment by nicolevasilevsky** [comment]
what do we do if an annotation is wrong and we want to change it? I see there is an annotation on LOINC 600-7 Bacteria identified in Blood by Culture, which is currently annotated with Recurrent staphylococcal infections, and I think this should be annotated with bacteremia instead.

**Comment by nicolevasilevsky** [comment]
Ok - i think I overwrote the original annotation with the new one. @kingmanzhang would you mind double checking?

**Comment by kingmanzhang** [comment]
@nicolevasilevsky  I looked at your commit. It appears you did have overwritten the old annotation, (which I created for demo purposes before "bacteremia" was available)

**Comment by nicolevasilevsky** [comment]
awesome! glad it's working. :)
