### ISSUE TITLE
LOINC 6071-5: Chicken meat IgE Ab [Units/volume] in Serum (update annotation)

### ISSUE THREAD

**Issue by callahantiff** [TheJacksonLaboratory/loinc2hpoAnnotation#91]
Change annotation from NOT(HP:0410227) to NOT(HP:0410233) -- (Increased anti-meat allergen IgE antibody level).

**Comment by callahantiff** [comment]
Additionally, change annotation for a high result from HP:0410227 to HP:0410233 -- (Increased anti-meat allergen IgE antibody level).

**Comment by kingmanzhang** [comment]
done
